os:
  - linux
  - osx
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
matrix:
  include:
    # Run e2e tests in Node.js 6.x
    - node_js: '6'
      env: MODE=e2e
sudo: required
dist: trusty
env:
  - NODE_ENV=PROD
before_install:
 - if [ "$TRAVIS_OS_NAME" == "linux" && $MODE == "e2e" ]; then export CHROME_BIN=/usr/bin/google-chrome; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" && $MODE == "e2e" ]; then export DISPLAY=:99.0; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" && $MODE == "e2e" ]; then sh -e /etc/init.d/xvfb start; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" && $MODE == "e2e" ]; then sudo apt-get update ; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" && $MODE == "e2e" ]; then sudo apt-get install -y libappindicator1 fonts-liberation; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" && $MODE == "e2e" ]; then wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" && $MODE == "e2e" ]; then sudo dpkg -i google-chrome*.deb; fi
 - if [ $TRAVIS_OS_NAME == osx ]; then rm '/usr/local/bin/f2py'; fi
 - if [ $TRAVIS_OS_NAME == osx ]; then rm -r '/usr/local/lib/python2.7/site-packages/numpy'; fi
 - if [ $TRAVIS_OS_NAME == osx ]; then brew install homebrew/science/opencv; fi
install:
  - npm install
  - if [ "$TRAVIS_OS_NAME" == "linux" && $MODE == "e2e" ]; then npm run install-selenium; fi
before_script:
  - npm run distribute
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then jdk_switcher use oraclejdk8; fi
  - npm run test-coveralls
  - if [ "$TRAVIS_OS_NAME" == "linux" && $MODE == "e2e" ]; then npm run test-e2e; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" && $MODE == "e2e" ]; then npm run lint; fi
